### ISSUE TITLE
将来的に整数ブロック, 小数ブロック, 文字列ブロックを実装する

### ISSUE THREAD

**Issue by mugicha9** [tsumiki-works/Pyramid#101]
入力の選別も一緒につける予定

**Comment by Shinonome517** [comment]
ここで型の情報をbackend側に受け取れるようにしたい。（そうすれば、Parseするときやevalするときに、backend側で型を評価する必要がなくなる）

**Comment by Shinonome517** [comment]
ほしいブロックは以下

* intブロック
* floatブロック
* stringブロック
* boolブロック
* listブロック

（listブロックの仕様については後日追記する）
