### ISSUE TITLE
Typescriptへの移行

### ISSUE THREAD

**Issue by mugicha9** [tsumiki-works/Pyramid#102]
~~中間発表2後に考える~~

**Comment by mugicha9** [comment]
現在進行中です
詳細はこのissueに紐づけてあるbranchを参照してください

**Comment by Tengu712** [comment]
WebGLのリファクタリングが完了しました。リクエストの仕様が変わっています。webgl/request.tsを参照してください。

TypeScriptではタプル型の初期化は必ずアノテーションが必要らしいです。凄く面倒ですが、お願いします。

```ts
let array = [0, 0];
let tupple: [number, number] = [0, 0];

function hoge(tupple: [number, number]): void {}
hoge([0, 0]); // error
hoge(tupple); // ok
```

**Comment by Tengu712** [comment]
バックエンドのリファクタリングが後はやるだけの状態になりました。また、局所変数の定義ができるようになりました。

**Comment by mugicha9** [comment]
フロントエンドのリファクタリング, 第一段階が完了しました。
以前と同様の操作ができるようになっています。
