### ISSUE TITLE
開発手法を取り入れる

### ISSUE THREAD

**Issue by mugicha9** [tsumiki-works/Pyramid#103]
現状、フロントエンドが学んだことがJavaScriptのみである。
そのため、開発手法という面からこの点を補完することが案に挙がった。

参照: https://www.nec-solutioninnovators.co.jp/column/01_agile.html

**Comment by narung56** [comment]
スクラム開発やりましょう。
参照:https://www.nec-solutioninnovators.co.jp/column/02_agile.html
