### ISSUE TITLE
除算ブロックが演算できない

### ISSUE THREAD

**Issue by Shinonome517** [tsumiki-works/Pyramid#105]
本日の実演で不都合が発生する可能性があるため報告

## エラー内容

数字ブロックを二つ繋げて、演算できる形になっているのにも関わらず、除算ブロック"/"の実行ができない

## エラー出力

> Pyramid Frontend error: the block type is not considered in `window.js`

## エラーを確認したversion

現在のmaserブランチのhead

commit id：d18703d54c6abe62eae22f09e0eded4bb81fa16e

**Comment by mugicha9** [comment]
fixed: #107
