### ISSUE TITLE
メニューバーの改良

### ISSUE THREAD

**Issue by narung56** [tsumiki-works/Pyramid#125]
- [x] メニューバーにラベル付け

**Comment by narung56** [comment]
よろしくお願いします。
@shomsato

**Comment by shomsato** [comment]
![image](https://user-images.githubusercontent.com/108119447/205249767-e0daef5b-7f82-498a-8e66-5651640065af.png)
こんな感じで、タブでブロックの種類を切り替える形にするかも。

**Comment by shomsato** [comment]
![アセット 9](https://user-images.githubusercontent.com/108119447/205292016-87892aad-99b6-4cae-b4e3-834f4ab849ff.png)
いまのところの案です @mugicha9

**Comment by shomsato** [comment]
![image](https://user-images.githubusercontent.com/108119447/206653549-711cce18-dcf8-43fc-abc5-00aa7516e7ff.png)
ソニー銀行のメニュー
