### ISSUE TITLE
組み込み関数の実装

### ISSUE THREAD

**Issue by Shinonome517** [tsumiki-works/Pyramid#128]
## 一項演算子

- [x] 論理否定

## 二項演算子

- [x] 加算
- [x]  減算
- [x]  乗算
- [x]  除算（切り捨て）
- [x]  あまり演算
- [x]  累乗演算
- [x] 論理積
- [x] 論理和

## 数学関数の実装

- [x] log
- [x] exp
- [x] sqrt
- [x] sin
- [x] cos
- [x] tan
~- [ ] 一変数微分~
~- [ ] 一変数定積分~

## リストオブジェクトに対する組み込み関数

~- [ ] map~
~- [ ] fold~

**Comment by narung56** [comment]
これマイルストーン上では、12/4までになっているけど
終わりそうですか？

終わらなそうであれば、締め切りを変更したほうが良いと思います。

**Comment by Shinonome517** [comment]
* 自分の作業が遅い
* Block Class のメソッド変更待ち
* Blockと型を対応させるために、Blockクラスの具象クラスを新たに追加している

等の理由で、Blockクラス関連に変更を加えています。

従って、締め切りをまず水曜日まで伸ばさせていただきます

**Comment by Shinonome517** [comment]
Listオブジェクトの組み込み関数は別issueで行う
