### ISSUE TITLE
PHPの導入

### ISSUE THREAD

**Issue by narung56** [tsumiki-works/Pyramid#157]
チュートリアルとドキュメントのSPA化を達成するために、全ページはAzeria-Worksのサーバーで管理し、そこにssh接続してPHPで開発しようというお話。

**Comment by shomsato** [comment]
ドキュメントはできてます
https://pyramid.224.works/doc/
https://pyramid.224.works/doc/?page=testpage

**Comment by shomsato** [comment]
チュートリアルにPHP使わないのであれば、このIssue閉じちゃってください

**Comment by narung56** [comment]
とりあえず閉じますか
