### ISSUE TITLE
型推論エンジンの作成

### ISSUE THREAD

**Issue by mugicha9** [tsumiki-works/Pyramid#171]
動的型付けにはしたくないが、完全な静的型付けでは実装や操作が非常に煩雑であることが判明したので、型推論を用いた型評価をすることになった。

以下タスク
- [ ] 型推論エンジンの完成
- [x] Pyramidへの適用
- [x] コードをきれいにする

**Comment by Tengu712** [comment]
漠然とできたのでクローズ。
