### ISSUE TITLE
比較演算子の作成

### ISSUE THREAD

**Issue by Shinonome517** [tsumiki-works/Pyramid#182]
## 演算子の用意

evaluationモジュールへの追加

- [x] ==
- [x] !=
- [x] >
- [x] <
- [x] >=
- [x] <=

## 組み込み演算子の登録

- [x] keyword.ts

## メニュータブへの追加

- [x] tutorial_database.ts

**Comment by narung56** [comment]
- [ ] πの追加

**Comment by Shinonome517** [comment]
## 追加作業

- [ ] envへの追加を簡略化
- [ ] keywordに渡すものを、PyramidObjectではなく演算そのものにする
