### ISSUE TITLE
ページの移動

### ISSUE THREAD

**Issue by narung56** [tsumiki-works/Pyramid#187]
スタートページが最初で

そこからチュートリアル、プレイグラウンド、ドキュメントに移動できるようにする。
それらのページからどこのページにでも移動が可能になると望ましい。

**Comment by shomsato** [comment]
dev/startpage で相対リンクの動作は確認済み

**Comment by shomsato** [comment]
あ、本番環境のドキュメントはPHPが動作しているので、そこは書き換えないで下さい。ヘッダーや内容は書換えていいです。

**Comment by shomsato** [comment]
#238
