### ISSUE TITLE
Listブロックにブロックを追加できない

### ISSUE THREAD

**Issue by Shinonome517** [tsumiki-works/Pyramid#195]
## 症状

Listブロックにリテラルブロックが追加できずに、リテラルブロックが右下に吹っ飛ぶ

1. ListブロックをmenutabからplayGroundにマウスドラッグする
2. Listブロックを右クリックし、引数の個数を2にする
3. LiteralブロックをMenuTabからPlayGroundにマウスドラッグする
4. LiteralブロックをListブロックにくっつけようとする（Listブロックのemptyブロック部分にLiteralブロックをマウスドラッグし、Literalブロックをマウスアウトする）とLiteralブロックが画面右下に吹っ飛ぶ

## 環境

ブラウザ：Google Chrome

## 発生箇所

12/18 17:09現在のmainブランチの最新コミット
commit id: ff9a0837588660cf6c73e6a3cbb5581bb8f2d286

**Comment by mugicha9** [comment]
fixed
