### ISSUE TITLE
現状==で比較できるのが数値のみになってしまう：比較演算子の仕様

### ISSUE THREAD

**Issue by Shinonome517** [tsumiki-works/Pyramid#196]
Comparison Operator Classに比較演算子を登録する際、

Number -> Number -> Bool （数値型のEqual）
String -> String -> Bool （文字列型のEqual）

二種類が必要になるが、関数オーバーロードがない現在では片方しか作ることができない。
文字列型も等しいか、等しくないかくらいは判定できた方がよいと思われるが、どのような実装にするべきであろうか？

**Comment by Tengu712** [comment]
オーバーロードをすぐに実装できる気がしないので、それぞれ別の比較演算子を作る。
