### ISSUE TITLE
チュートリアルの足りない部分

### ISSUE THREAD

**Issue by shomsato** [tsumiki-works/Pyramid#235]
発表後に修正しよう
- [ ] 関数ブロックの使い方の画像を表示する
- [x] 数字の編集のやり方が説明されていない
- [x] 問題1-5の評価でチェックがつかない
- [x] 関数定義ブロックの使い方がちゃんと説明されていないのでよく分からない
- [x] 最新(発表時点)のメインブランチ、なぜか1-1のチェックがつかなくなりました　![image](https://user-images.githubusercontent.com/108119447/208897643-877e22ff-0f1a-41d9-a4ac-ad13a88cef44.png)

**Comment by shomsato** [comment]
numをi32とf32に変えたから数字を扱うチュートリアルバグった説

**Comment by mugicha9** [comment]
numを変えたからじゃなくて+がSymbolBlockからAddBlockになったからだね(HTMLのタグの名前が変わった)

**Comment by shomsato** [comment]
![image](https://user-images.githubusercontent.com/108119447/209065490-cda837ef-5088-422d-b262-d87095a9012c.png)

関数の使い方、ガチで分からなくなった😭

**Comment by narung56** [comment]
何色がどのようなタイプのブロックであるかの説明はチュートリアルじゃなくてドキュメントとかで良い気がしました。

**Comment by narung56** [comment]
とりあえず1-6,7の誘導をわかりやすくします。

**Comment by shomsato** [comment]
チュートリアルにデフォルトで0が入ってるのが数字だよみたいなこと書いたので色は書かなくていいですねぇ。ドキュメントには、ブロックのプレビューみたいなのを載せようと思ってます。
![Screenshot_20230112-161735-02](https://user-images.githubusercontent.com/108119447/212002404-9b57616a-dc68-4d59-810e-eaca37fdc515.jpeg)

**Comment by narung56** [comment]
1-1の問題のチェックリストにチェックつかないけど

これはまだ修正してないってことで良い？

**Comment by mugicha9** [comment]
修正したと思います
最新のpull&npx tscの確認お願いします

**Comment by narung56** [comment]
普通にしてないことに気づいて消しました()
連絡ありがとうございます。
