### ISSUE TITLE
コンソールの背景の「Console」の表示

### ISSUE THREAD

**Issue by Tengu712** [tsumiki-works/Pyramid#49]
SVGからPNGへの移行につき。

**Comment by narung56** [comment]
これって、結局必要ある？

**Comment by shomsato** [comment]
まずはメニューバーとかヘッダーとかの装飾を優先はしたほうがいいかもね。そっちの機能が増えるとコンソールまで装飾してたら画面ごちゃごちゃになりそう。メニューバーのブロックの種類とかあまり増やせず寂しい画面のまま完成を迎えそうになったら、コンソールの装飾をするといいかも。
あと、結局コンソールはDOMになったので、当初のようにSVGでできるかも。
