### ISSUE TITLE
四則演算の実装

### ISSUE THREAD

**Issue by Shinonome517** [tsumiki-works/Pyramid#85]
中間発表の実演のために、+, -, *, /, %
を実装する

**Comment by Shinonome517** [comment]
@Tengu712 

二点確認及び質問がある。

## 型の判定について

Parseされた後の文字列リテラルから、Pyramidにおける型を判別するために、正規表現のパターンマッチを行いたい。そのためにRustのregexクレートを使いたいが、問題ないか？

例）
文字列：^\\".*\\"$
浮動小数型：[+-]?\d+(?:\.\d+)?

[クレートの種類](https://docs.rs/regex/latest/regex/)
[ソースコード(ライセンスはMITとApach)](https://github.com/rust-lang/regex)

## PyramidObject構造体の構造について

PyramidObject型にtype_id = Nilを用意する際、value にNullを許容するためにOption型のNoneを用いたが、pullreqに対して指摘が入った。
改良するとして、type_id = Nilの場合のvalueは何にすべきか？

**Comment by Shinonome517** [comment]
追伸
先日のPullreqで型の実装が終わったといったのは嘘でした。
すみません。

**Comment by Tengu712** [comment]
# regexクレートの利用について

regexクレートは、Rust公式のクレートであるので、利用しても問題ないと思います。

ただし、まず、正規表現エンジンの必要性を疑うべきです。正規表現エンジンは往々にして遅いので、regexがよほど速くない限り、なるべく使いたくない。

今回解析したい字句は、たかだか以下くらいで、わざわざ正規表現エンジンを使うまでの解析とは(今のぼくの見立てでは)思えません。以下は優先度降順。

* 型名(完全一致)
* 整数リテラル(負値は下に加えて-の一文字の前方一致)
  * 十進数(0-9の繰り返し)
  * 二進数(0bの二文字前方一致と0-1の繰り返し)
  * 十六進数(0xの二文字前方一致と0-Fの繰り返し)
* 小数リテラル(.を一文字だけ含む0-9の繰り返し)
* 文字列リテラル("の一文字前方及び後方一致と任意文字の繰り返し)
* 識別子(区切り文字である(と)と\s以外の任意の文字の繰り返し)

`0012`という整数リテラルを許さないにしても。上の例では、前から文字を順番に読めば十分なので、コード量を気にしない限り簡単に解析できます。

ただ、使いたいなら、使ってください。ぼくも効率のいい実装をしているとは、胸を張って言えないので、パフォーマンスの観点で指摘する権利はないと自覚しています。

> 一応補足までに、「いや普通言語作るとき正規表現で字句解析するやん!!」っていう突っ込みを期待して、その返答。
> 
> 大前提として、コンパイラの字句解析器の正規表現エンジンはランタイムで初期化されるものではない。わざわざCとlexに分けられているのは、lexによって最適化されたNFAをCに埋め込むためでもあると思う。仮にregexがランタイムでNFAを作るなら、パフォーマンスが悪いので、使うべきでは絶対にない。
> 
> 字句解析は普通の言語では煩雑になりやすい。例えばCでは`int a=1+1;`と`int   a=\n\t1 +1;`は等位に解析されなければならず、また`inta=1+1;`とは区別されなくてはならない。これを愚直に解析していると結構だるい。
> 
> 一方S式は区切り文字が(と)と\sだけなので、面倒な解析がそもそも生じない。(せいぜい`(a)`と`( a )`を等位に評価するくらい)。そうであるから、残された部分も簡単な解析しかない。(と思う)

# Nil時のPyramidObject.valueに対して

`String`型の`"nil"`で良いです。つまり以下。

```rust
PyramidObject {
    type_id: PyramidType::Nil,
    value: String::from("nil");
}
```

まずNil型は値を持たないはずなので、値を参照される事態があればバグです。いかなる場合も先に型を判定すれば、Nil型をはじけるので、valueはなんだって構いません。`"hoge"`でもいい。

**Comment by Shinonome517** [comment]
## regexクレートについて

確かに、高々1シンボルの解析のために、regexを用いるのは大げさでした。
実行時にregexで解析するのと、コンパイル時にregexで解析することの違いも納得しました。
regexを用いずに解析してみます。問題が起きた場合はまた相談します。

## Nil時のvalueの値について

承知しました。
上記の通りに修正します。
