### ISSUE TITLE
数字ブロックを演算子ブロックの上にくっつけようとした時に起こるバグ

### ISSUE THREAD

**Issue by narung56** [tsumiki-works/Pyramid#91]
数字ブロックを演算子ブロックの上にくっつけようとするとアラートが出ますが、

その後に数字ブロックをクリックすると良くわからない場所に移動した後、なんの操作も行えず、演算子ブロックをクリックすると、数字ブロックが消えます。

演算子ブロックをクリックした場合はすぐに数字ブロックが消えます。

**Comment by mugicha9** [comment]
#98 で修正済み
