### ISSUE TITLE
Braveブラウザ使用時、コンテキストメニュー無効化が効いてない

### ISSUE THREAD

**Issue by shomsato** [tsumiki-works/Pyramid#96]
![image](https://user-images.githubusercontent.com/108119447/201620755-c2e8aa33-cee5-4804-a7cd-9a31f374d45b.png)
Braveブラウザで右クリックするとPyramidのポップアップに被るようにブラウザ側のコンテキストメニューが出てきます。まあBraveブラウザはmiroやtrading viewでも右クリックするとコンテキストメニュー出てくるので、Braveは非推奨環境ということにしてもいいかもしれません。
でも、GoogleマップやGoogleスライド、Yahoo!地図、binanceなどではコンテキストメニュー出ないようになっているので、別の方法で無効化しているのかも。

**Comment by mugicha9** [comment]
おそらくeventに対してprevent defaultを呼び出すことを忘れていたからだと思います
この辺り含め修正しておきます。

**Comment by mugicha9** [comment]
上のコメントは忘れてください。
私の環境ではbraveブラウザを使用してもコンテキストメニューの表示が再現できませんでした...

**Comment by shomsato** [comment]
そうなんですね。ブラウザのアプデとかで直るかもしれないから、時間置いて試してみます。

**Comment by shomsato** [comment]
右クリック無効化解除の拡張機能を有効にしたままだっただけでした。お騒がせしてすみませんでした。
